Update deploy-pages.yml

diff --git a/.github/workflows/deploy-pages.yml b/.github/workflows/deploy-pages.yml
--- a/.github/workflows/deploy-pages.yml
+++ b/.github/workflows/deploy-pages.yml
@@ -22,16 +22,16 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Inject runtime variables
-        env:
-          GOOGLE_SHEET_WEBHOOK_URL: ${{ secrets.GOOGLE_SHEET_WEBHOOK_URL }}
-        run: |
-          if [ -z "$GOOGLE_SHEET_WEBHOOK_URL" ]; then
-            echo "Secret GOOGLE_SHEET_WEBHOOK_URL is missing"
-            exit 1
-          fi
+      # - name: Inject runtime variables
+      #   env:
+      #     GOOGLE_SHEET_WEBHOOK_URL: ${{ secrets.GOOGLE_SHEET_WEBHOOK_URL }}
+      #   run: |
+      #     if [ -z "$GOOGLE_SHEET_WEBHOOK_URL" ]; then
+      #       echo "Secret GOOGLE_SHEET_WEBHOOK_URL is missing"
+      #       exit 1
+      #     fi
 
-          sed -i "s|__GOOGLE_SHEET_WEBHOOK_URL__|$GOOGLE_SHEET_WEBHOOK_URL|g" index.html
+      #     sed -i "s|__GOOGLE_SHEET_WEBHOOK_URL__|$GOOGLE_SHEET_WEBHOOK_URL|g" index.html
 
       - name: Setup Pages
         uses: actions/configure-pages@v5
